spring:
  datasource:
    url: ${ORDER_SERVICE_DATASOURCE_URL:jdbc:postgresql://localhost:5432/microservices?currentSchema=order_service}
    driver-class-name: org.postgresql.Driver
    username: ${ORDER_SERVICE_DATASOURCE_USERNAME:micro}
    password: ${ORDER_SERVICE_DATASOURCE_PASSWORD:micro}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: order_service
        format_sql: true
    open-in-view: false
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
