spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/orders_test
    username: postgres
    password: ""
  jpa:
    hibernate:
      ddl-auto: create-drop # Для тестов лучше create-drop, чтобы каждый запуск был на чистой схеме
  liquibase:
    enabled: false # Отключаем Liquibase для тестов