# Общие настройки по умолчанию. Средо-специфичные настройки вынесены в профили.
logging:
  level:
    org.springframework.orm.jpa: INFO

spring:
  kafka:
    bootstrap-servers: localhost:9092

app:
  kafka:
    topics:
      orders-created: orders.created
