logging:
  level:
    org.springframework.orm.jpa: INFO

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/inventory_db
    username: postgres
    password:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
