spring:
  datasource:
    url: jdbc:h2:mem:inventory;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.springframework.orm.jpa: INFO
