spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/inventory_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

